# Generated by Django 4.2.3 on 2024-06-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentimentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentimentanalysis',
            name='sentiment_data',
            field=models.CharField(max_length=10),
        ),
    ]
